package MusicApp;

import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author adamp
 */
public class musicAppGUI extends javax.swing.JFrame {

    final ALMethods alMethods;
    final DLList myList;
    private int count = 0;

    /**
     * Creates new form musicAppGUI
     */
    public musicAppGUI() {
        initComponents();
        alMethods = new ALMethods();
        myList = new DLList();
        ImageIcon i = new ImageIcon("speaker.png");
        iconLabel.setIcon(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addLikedSongBtn = new javax.swing.JButton();
        addSongTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputBox = new javax.swing.JTextArea();
        headingLabel = new javax.swing.JLabel();
        deleteLikedSongBtn = new javax.swing.JButton();
        searchLikedSongBtn = new javax.swing.JButton();
        showPopPlaylistBtn = new javax.swing.JButton();
        showRapPlaylistBtn = new javax.swing.JButton();
        iconLabel = new javax.swing.JLabel();
        showLikedSongsBtn = new javax.swing.JButton();
        addToPopPlaylistBtn = new javax.swing.JButton();
        addToRapPlaylistBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        addLikedSongBtn.setText("Add Song to Liked Playlist");
        addLikedSongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLikedSongBtnActionPerformed(evt);
            }
        });

        addSongTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSongTextFieldActionPerformed(evt);
            }
        });

        outputBox.setEditable(false);
        outputBox.setColumns(20);
        outputBox.setRows(5);
        jScrollPane1.setViewportView(outputBox);

        headingLabel.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        headingLabel.setText("Music Playlist App");

        deleteLikedSongBtn.setText("Delete Liked Song");
        deleteLikedSongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLikedSongBtnActionPerformed(evt);
            }
        });

        searchLikedSongBtn.setText("Search Liked Song");
        searchLikedSongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchLikedSongBtnActionPerformed(evt);
            }
        });

        showPopPlaylistBtn.setText("Show Pop Playlist");
        showPopPlaylistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPopPlaylistBtnActionPerformed(evt);
            }
        });

        showRapPlaylistBtn.setText("Show Rap Playlist");
        showRapPlaylistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRapPlaylistBtnActionPerformed(evt);
            }
        });

        showLikedSongsBtn.setText("Show Liked Playlist");
        showLikedSongsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showLikedSongsBtnActionPerformed(evt);
            }
        });

        addToPopPlaylistBtn.setText("Add to Pop Playlist");
        addToPopPlaylistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToPopPlaylistBtnActionPerformed(evt);
            }
        });

        addToRapPlaylistBtn.setText("Add to Rap Playlist");
        addToRapPlaylistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToRapPlaylistBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(headingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addLikedSongBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addSongTextField)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(deleteLikedSongBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showPopPlaylistBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showRapPlaylistBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchLikedSongBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showLikedSongsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addToPopPlaylistBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addToRapPlaylistBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addSongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addLikedSongBtn))
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchLikedSongBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteLikedSongBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showLikedSongsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addToPopPlaylistBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addToRapPlaylistBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showPopPlaylistBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showRapPlaylistBtn)))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addLikedSongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLikedSongBtnActionPerformed
        String userInput = addSongTextField.getText();
        if (userInput.isBlank()) {
            outputBox.setText("Please enter a valid song name.");
        } else {
            myList.addSong(count, userInput);
            count++;
            outputBox.setText(userInput + " is added to your liked Playlist.");
        }
    }//GEN-LAST:event_addLikedSongBtnActionPerformed

    private void addSongTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSongTextFieldActionPerformed

    }//GEN-LAST:event_addSongTextFieldActionPerformed

    private void deleteLikedSongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLikedSongBtnActionPerformed
        //removes last song enter from user
        if (count > 0) {
            myList.removeSong(myList.playlistSize());
            count--;
            outputBox.setText(myList.printAllSongs());
        } else if (count == 0) {
            outputBox.setText("Your liked songs playlist is already empty.");
        }
    }//GEN-LAST:event_deleteLikedSongBtnActionPerformed

    private void searchLikedSongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchLikedSongBtnActionPerformed
        String userInput = addSongTextField.getText();
        boolean found = false;
        int position = -1;
        //loops through songs to find the same one searched by user
        for (int i = 0; i < count; i++) {
            if (myList.getSongs(i).equals(userInput)) {
                found = true;
                position = i + 1;
                break;
            }
        }
        
        if (found) {
            outputBox.setText(userInput + " found at position " + position + " in the list.");
        } else if (addSongTextField.getText().isEmpty()) {
            outputBox.setText("There is no song to find in your liked Playlist.");
        } else {
            outputBox.setText(userInput + " not found in the list.");
        }
    }//GEN-LAST:event_searchLikedSongBtnActionPerformed

    private void showPopPlaylistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPopPlaylistBtnActionPerformed
        String popPlaylist = alMethods.showAllPopSongs();
        outputBox.setText(popPlaylist);
    }//GEN-LAST:event_showPopPlaylistBtnActionPerformed

    private void showRapPlaylistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRapPlaylistBtnActionPerformed
        String rapPlaylist = alMethods.showAllRapSongs();
        outputBox.setText(rapPlaylist);
    }//GEN-LAST:event_showRapPlaylistBtnActionPerformed

    private void showLikedSongsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showLikedSongsBtnActionPerformed
        String allSongs = myList.printAllSongs();
        outputBox.setText(allSongs + "There are " + count + " liked songs in this playlist");
    }//GEN-LAST:event_showLikedSongsBtnActionPerformed

    private void addToPopPlaylistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToPopPlaylistBtnActionPerformed
        String popSong = addSongTextField.getText();
        String result = alMethods.addPopSong(popSong);
        outputBox.setText(result);
    }//GEN-LAST:event_addToPopPlaylistBtnActionPerformed

    private void addToRapPlaylistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToRapPlaylistBtnActionPerformed
        String rapSong = addSongTextField.getText();
        String result = alMethods.addRapSong(rapSong);
        outputBox.setText(result);
    }//GEN-LAST:event_addToRapPlaylistBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(musicAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(musicAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(musicAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musicAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLikedSongBtn;
    private javax.swing.JTextField addSongTextField;
    private javax.swing.JButton addToPopPlaylistBtn;
    private javax.swing.JButton addToRapPlaylistBtn;
    private javax.swing.JButton deleteLikedSongBtn;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputBox;
    private javax.swing.JButton searchLikedSongBtn;
    private javax.swing.JButton showLikedSongsBtn;
    private javax.swing.JButton showPopPlaylistBtn;
    private javax.swing.JButton showRapPlaylistBtn;
    // End of variables declaration//GEN-END:variables
}
